project:
  type: website
  output-dir: docs

website:
  title: "Justin Kadi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work Experience
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

